when:
  event: [push, pull_request, manual]

steps:
  lint:
    image: golang:1.26-alpine
    failure: ignore
    commands:
      - apk add --no-cache git build-base
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b /usr/local/bin v2.12.2
      - golangci-lint run --verbose --timeout 5m

  security:
    image: securego/gosec:2.24.6
    failure: ignore
    environment:
      GOTOOLCHAIN: auto
    commands:
      - apk add --no-cache git
      - gosec ./...

  test:
    image: golang:1.26-alpine
    commands:
      - apk add --no-cache git build-base
      - go test -v ./...

  build:
    image: golang:1.26-alpine
    commands:
      - CGO_ENABLED=0 go build -ldflags="-s -w" -o heroctl ./cmd/heroctl

  release:
    image: woodpeckerci/plugin-gitea-release
    failure: ignore
    when:
      event: tag
      ref: refs/tags/v*
    settings:
      api_key:
        from_secret: codeberg_token
      base_url: https://codeberg.org
      files:
        - heroctl
      title: ${CI_COMMIT_TAG}
      generate_release_notes: true

  docker:
    image: woodpeckerci/plugin-docker-buildx:6.1.0
    privileged: true
    when:
      event: tag
      ref: refs/tags/v*
    settings:
      registry: codeberg.org
      repo: codeberg.org/infraheroes/heroctl
      username: dominikludwig1995
      password:
        from_secret: codeberg_token
      platforms: linux/amd64,linux/arm64
      tags:
        - ${CI_COMMIT_TAG}
        - latest
